### ISSUE TITLE
Endianness of integer literals

### ISSUE THREAD

**Issue by kevinramharak** [Francessco121/hlml-toolkit#13]
So i was wondering about how you are planning to deal with the endianness of integer literals.

**Comment by Francessco121** [comment]
Since MAR's byte-code language is the target, it would be the same endianness that it uses. I haven't started work on compiling to binary just yet, so I'm not actually sure which it is lol.

**Comment by kevinramharak** [comment]
I know the source code is stored in Java char's. These are 16 bit integers as far as i know. This is something to keep note of when doing (assembly time) math. Also means a integer literal < 255 wastes 1 byte of space. This could be optimised. Its a long term thing but something to note i guess.

**Comment by Francessco121** [comment]
It does technically waste 1 byte of space, but this is intentional ([see the MAR docs](https://github.com/simon987/Much-Assembly-Required/wiki/Instruction-Encoding)). All parts of an instruction are 16-bit. If it could vary, the VM would have to somehow figure out the size of each operand, which would be weird and just take up more space with metadata. Padding < 255 values with the extra byte also lets memory addresses line up correctly.

The MMAR assembler already parses integer literals the same way MAR does (as far as endianness goes). I'm not sure I understand how this would effect assemble-time math though?

**Comment by Francessco121** [comment]
Turns out it's big-endian, as that's what Java uses.
